/*
 * generated by Xtext
 */
package de.cau.cs.kieler.klassviz.text.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import de.cau.cs.kieler.klassviz.text.ui.internal.ClassDataActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ClassDataExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ClassDataActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ClassDataActivator.getInstance().getInjector(ClassDataActivator.DE_CAU_CS_KIELER_KLASSVIZ_TEXT_CLASSDATA);
	}
	
}
