/*
* generated by Xtext
*/
package de.cau.cs.kieler.klassviz.text.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import de.cau.cs.kieler.klassviz.text.services.ClassDataGrammarAccess;

public class ClassDataParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ClassDataGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected de.cau.cs.kieler.klassviz.text.parser.antlr.internal.InternalClassDataParser createParser(XtextTokenStream stream) {
		return new de.cau.cs.kieler.klassviz.text.parser.antlr.internal.InternalClassDataParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "KClassModel";
	}
	
	public ClassDataGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ClassDataGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
